In [1]:
! python -m pip install numpy

In [2]:
#import 

import numpy as np

In [15]:
a=np.array([[1,2,3,4,5],[2,3,2,1,2]])

In [16]:
a

array([[1, 2, 3, 4, 5],
       [2, 3, 2, 1, 2]])

In [6]:
b=np.array(range(5))

In [7]:
b

array([0, 1, 2, 3, 4])

In [12]:
c=np.array([range(5),range(15,20)]) # if the structure is not even then it will make the list as the object and if it will be even then it will make the array

In [13]:
c

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [14]:
type(c)

numpy.ndarray

In [16]:
a.dtype

dtype('int32')

In [30]:
a=np.arange(0,50)

In [35]:
b=a.reshape(10,-1)


In [36]:
b.ndim  #it will shows up the dimension

2

In [42]:
b[:,2]

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [24]:
a[:,1]=0

In [25]:
a

array([[ 0,  0,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10,  0, 12, 13, 14],
       [15,  0, 17, 18, 19],
       [20,  0, 22, 23, 24],
       [25,  0, 27, 28, 29],
       [30,  0, 32, 33, 34],
       [35,  0, 37, 38, 39],
       [40,  0, 42, 43, 44],
       [45,  0, 47, 48, 49]])

In [26]:
a[:,1:3]=0

In [27]:
a

array([[ 0,  0,  0,  3,  4],
       [ 5,  0,  0,  8,  9],
       [10,  0,  0, 13, 14],
       [15,  0,  0, 18, 19],
       [20,  0,  0, 23, 24],
       [25,  0,  0, 28, 29],
       [30,  0,  0, 33, 34],
       [35,  0,  0, 38, 39],
       [40,  0,  0, 43, 44],
       [45,  0,  0, 48, 49]])

In [28]:
a[:,1:7]=0

In [29]:
a

array([[ 0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [15,  0,  0,  0,  0],
       [20,  0,  0,  0,  0],
       [25,  0,  0,  0,  0],
       [30,  0,  0,  0,  0],
       [35,  0,  0,  0,  0],
       [40,  0,  0,  0,  0],
       [45,  0,  0,  0,  0]])

In [30]:
# hstack & vstack horizontal and vertical stacking

In [31]:
# in horizontal stack rows has to be same and in vertical stacking colomn has to be same

In [44]:
one=np.arange(20).reshape(5,-1)
two=np.arange(40,60).reshape(5,-1)

In [45]:
one


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
two

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [47]:
np.hstack([one,two])

array([[ 0,  1,  2,  3, 40, 41, 42, 43],
       [ 4,  5,  6,  7, 44, 45, 46, 47],
       [ 8,  9, 10, 11, 48, 49, 50, 51],
       [12, 13, 14, 15, 52, 53, 54, 55],
       [16, 17, 18, 19, 56, 57, 58, 59]])

In [48]:
np.vstack([one,two])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [49]:
np.stack((one,two),axis=1)   #only for combining two array according to axis

array([[[ 0,  1,  2,  3],
        [40, 41, 42, 43]],

       [[ 4,  5,  6,  7],
        [44, 45, 46, 47]],

       [[ 8,  9, 10, 11],
        [48, 49, 50, 51]],

       [[12, 13, 14, 15],
        [52, 53, 54, 55]],

       [[16, 17, 18, 19],
        [56, 57, 58, 59]]])

In [50]:
# Brodcasting

In [51]:
one+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [52]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
two

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [54]:
one+two

array([[40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62],
       [64, 66, 68, 70],
       [72, 74, 76, 78]])

In [55]:
## Adding two array of different dimension then it will do it one row by one

In [56]:
three=np.array([1,2,3,4])

In [57]:
one+three

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23]])

In [58]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
np.sin(one)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [60]:
np.min(one,axis=1)

array([ 0,  4,  8, 12, 16])

In [61]:
np.min(one,axis=0)

array([0, 1, 2, 3])

In [62]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
np.mean(one,axis=1) # for mean

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [66]:
# for standard deviation

np.std(one,axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [67]:
# for sin theta and cos theta

In [68]:
np.sin(90)

0.8939966636005579

In [69]:
np.cos(90)

-0.4480736161291701

In [70]:
data=np.linspace(0,2*np.pi,10).reshape([5,2])  #Linesspacing ###doubt

In [71]:
data

array([[0.        , 0.6981317 ],
       [1.3962634 , 2.0943951 ],
       [2.7925268 , 3.4906585 ],
       [4.1887902 , 4.88692191],
       [5.58505361, 6.28318531]])

In [72]:
np.sin(data)

array([[ 0.00000000e+00,  6.42787610e-01],
       [ 9.84807753e-01,  8.66025404e-01],
       [ 3.42020143e-01, -3.42020143e-01],
       [-8.66025404e-01, -9.84807753e-01],
       [-6.42787610e-01, -2.44929360e-16]])