In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs
from sklearn.preprocessing import OneHotEncoder

In [18]:
data=np.random.randint(0,10,10)

In [31]:
ohe=OneHotEncoder(categories="auto")

In [33]:
ohe.fit(data.reshape(-1,1))

OneHotEncoder(categorical_features=None, categories='auto', drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [34]:
ohe.categories_

[array([0, 2, 4, 5, 6, 7, 9])]

In [35]:
print(ohe.transform(data.reshape(-1,1)))

  (0, 4)	1.0
  (1, 3)	1.0
  (2, 6)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
  (8, 5)	1.0
  (9, 1)	1.0


In [37]:
print(ohe.transform(data.reshape(-1,1)).todense())

[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
